<div class="container">
	<input type="text" class="form-control" placeholder="Digite o nome do produto ou referência" id="search">
</div>

<div class="container">
	<div class="table-responsive">
		<table class="table table-hover">
			<thead>
				<tr>
					<th scope="col">Referência</th>
					<th scope="col">Nome</th>
					<th scope="col">Preço</th>
					<th scope="col">Fornecedores</th>
					<th scope="col">Opções</th>
				</tr>
			</thead>
			<tbody id="body-table">
			</tbody>
		</table>
	</div>
</div>