<div class="container">
	<h3 class="title-container">Produtos Selecionados</h3>

	<a href="/" class="d-block text-right my-2 voltar"><i class="fas fa-long-arrow-alt-left"></i> Voltar</a>
	<div class="table-responsive">
		<table class="table table-hover">
			<thead>
				<tr>
					<th scope="col">Referência</th>
					<th scope="col">Nome</th>
					<th scope="col">Preço</th>
					<th scope="col">Fornecedores</th>
				</tr>
			</thead>
			<tbody id="body-table">
			</tbody>
		</table>

		<p>
			<strong>Total: <span id="total">400,00</span></strong>
		</p>
	</div>
</div>

<a href="/dados_venda" class="btn btn-primary mt-3 w-25 mx-auto d-block" id="btn-finalizar">Próximo</a>