<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta name="keywords" content="HTML, CSS, JavaScript, PHP, MySql">
	<meta name="author" content="Carlos Alexandre">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta charset="utf-8">

	<!-- Bootstrap Css -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

	<!-- Font Awesome -->
	<script src="https://kit.fontawesome.com/90bfac5e12.js" crossorigin="anonymous"></script>

	<!-- Estilo Css -->
	<link rel='stylesheet' type='text/css' href='/css/estilo.css'>
	<?php 
		if (isset($this->view->css)) {
			foreach ($this->view->css as $indice => $estilo) {
				echo "<link rel='stylesheet' type='text/css' href='/css/". $estilo .".css'>";
			}
		}
	?>
	<link rel='stylesheet' type='text/css' href='/css/media-query.css'>

	<title><?= isset($this->view->title) ? trim($this->view->title).' - Carlos Alexandre' : 'Miniframework'; ?></title>
	<link rel="icon" href="">

	<!-- Fonts -->
	<link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Domine:wght@600&display=swap" rel="stylesheet">

	<!-- Jquery -->
	<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>

	<!-- Bootstrap JS -->
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</head>
<body>

	<header class="content">
		<nav class="navbar navbar-expand-sm" id="header">

			<a href="/" class="navbar-brand logo-text">Carlos Alexandre</a>

			<button class="navbar-toggler" id="hamburguer" type="button" data-toggle="collapse" data-target="#menu" aria-label="Toggle navigation">
				<i class="fas fa-bars text-white"></i>
			</button>

			<div class="collapse navbar-collapse" id="menu">
				<ul class="navbar-nav d-flex justify-content-end mr-5 w-100">
					<li class="nav-item">
						<a href="/" class="nav-link">Home</a>
					</li>
					<li class="nav-item">
						<a href="/vendas" class="nav-link">Vendas</a>
					</li>
				</ul>

				<i class="fas fa-shopping-cart ml-auto" id="icon-shop">
				</i>

				<div id="help-div" class="d-none">
					<div class="box-help">
						<ul id="list-itens">	

							<div id="group-itens">
								
							</div>
						</ul>
					</div>
				</div>
			</div>
		</nav>
	</header>


	<?= $this->content() ?>

	<script src='/js/script.js'></script>
	<?php
		if (isset($this->view->js)) {
			foreach ($this->view->js as $indice => $script) {
				echo "<script src='/js/". $script .".js'></script>";
			}
		}
	?>
</body>
</html>